version: '3'
services:
    mysql:
        image: mysql:8.0.34
        restart: always
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: db
            MYSQL_USER: user      
            MYSQL_PASSWORD: password
            MYSQL_ROOT_HOST: '%'
            MYSQL_ROOT_PASSWORD: root
            TZ: Asia/Seoul
        command:
            - --character-set-server=utf8mb4
            - --collation-server=utf8mb4_unicode_ci
        volumes:
            - ./database/mysql/data/mysql/:/var/lib/mysql

    redis:
        image: redis
        restart: always
        hostname: redis
        ports:
            - 6379:6379
        volumes:
            - ./database/redis/data/mysql/:/data