server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db
    username: user
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    data:
      host: localhost
      port: 6379

mybatis:
  mapper-locations: classpath:mapper/**/*.xml

jwt:
  secret: cjnafcBC23Cdcj2194CJDNAJjaJHCOA773CNAJJCsdc3JCC11
  accessTokenMinute : 30
  refreshTokenDay : 7