server:
  port: 9000

spring:
  datasource:
    url: ${DB_CONNECTION_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    data:
      host: redis
      port: 6379

mybatis:
  mapper-locations: classpath:mapper/**/*.xml